pipeline {
    agent any

    stages {

        stage('Install Python Dependencies') {
            steps {
                sh '''
                python3 --version
                python3 -m ensurepip --upgrade
                python3 -m pip install flask
                '''
            }
        }

        stage('Run Application') {
            steps {
                sh '''
                python3 NIrma/app.py
                '''
            }
        }

    }
}
