pipeline {
    agent any

    stages {

        stage('Install Python Dependencies') {
            steps {
                sh '''
                python3 --version
                apt update
                apt install -y python3-pip
                pip3 install flask
                '''
            }
        }

        stage('Run Application') {
            steps {
                sh '''
                python3 NIrma/app.py
                '''
            }
        }

    }
}
